### ISSUE TITLE
横幅が450px以下のとき、ドロップダウンメニューを表示するとレイアウトが崩れる

### ISSUE THREAD

**Issue by Hayao0819** [yamader/minskey#20]
![image](https://github.com/yamader/minskey/assets/32128205/b1dab98e-4937-4918-a0bc-1d32a47ba80a)

**Comment by Hayao0819** [comment]
表示されてるノート酷すぎて後悔

**Comment by Hayao0819** [comment]
Xiaomi POCO X4 Pro 5G Brave


![Screenshot_20240108-184438_Brave.png](https://github.com/yamader/minskey/assets/32128205/d0ed37d4-110d-4867-a544-cf014b8766de)

**Comment by yamader** [comment]
今気付いた
radixが悪かったりする……？

**Comment by Hayao0819** [comment]
全然わからん
詳しく調査してないので

**Comment by Hayao0819** [comment]
ユーザー名とリンクの折り返しの設定が必要かもしれない


<img width="388" alt="image" src="https://github.com/yamader/minskey/assets/32128205/22684649-f68c-4271-b322-f4a17f9e373a">

**Comment by yamader** [comment]
ユーザー名どうしようね

**Comment by Hayao0819** [comment]
暫定で改行させたけど正直カッコ悪いので悩み中

**Comment by Hayao0819** [comment]
new-layoutで改善されるといいな
