### ISSUE TITLE
Discuss: 複数アカウントの実装方法についての議論

### ISSUE THREAD

**Issue by Hayao0819** [yamader/minskey#23]
現状accountsで配列を持ち、currentAccountでそのインデックスを保持する実装にしている。

#18 

![image](https://github.com/yamader/minskey/assets/32128205/357d3fb3-9b5c-4b60-a42a-96e2d3a1e459)

**Comment by Hayao0819** [comment]
アクセストークン思いっきり晒してて鬱。トークン無効化しました。

**Comment by Hayao0819** [comment]
現在アカウント切り替えのUIを実装しているのだが、問題点として次が挙げられる。

- アカウント名の取得にAPIを叩く必要があるのだが、現状の構成だとapiAtomでしかAPIを叩けない
	- アカウントを指定してAPIを叩くラッパーを作る？
		- 無秩序になってしまわないか？
- 現在HookではuseAccountsでアカウント一覧を管理、useAuthで現在の情報を管理している
  - 全部まとめたほうがいい？
- currentAccountはaccountsのインデックスを保持している
  - 範囲外の値を保持している場合の例外処理の実装が曖昧かもしれない
  - 現在のアカウント情報の取得のためにatomを2つ取得する必要がある

**Comment by yamader** [comment]
基本的に、同時に使えるアカウントは1つでいい
アカウントを指定してAPI叩く機能はとりあえず無しでいこう(暇になってきたらやってもいい 

それはそうと、カスタムフック増やしまくるのだるくなってきたからuseAtom解禁するかなぁ
jotaiから乗り換える心配はなさげだし

**Comment by Hayao0819** [comment]
カスタムフックなんで作ってるんだろうって思ったけど状態管理とアプリロジックの分離が目的だったのか…

**Comment by Hayao0819** [comment]
>> 基本的に、同時に使えるアカウントは1つでいい
アカウント追加時に名前とアイコンをどこかにキャッシュしておけばいいかな

**Comment by yamader** [comment]
せやねー
ただ，自分のアカウント以外のアカウントもキャッシュするかもしれないので普通にsessionStorageな`user[]`のatomかなんかを生やす感じかな

**Comment by Hayao0819** [comment]
profileAtomを複垢対応させたいんだけど、現状のaccoutsAtomがHostとTokenしかないので、やっぱり各Tokenで`i`で情報を取得する必要がありそう

**Comment by yamader** [comment]
どっちにせよそうなるな

**Comment by yamader** [comment]
どね
