### ISSUE TITLE
GTLの内容が表示されない

### ISSUE THREAD

**Issue by Hayao0819** [yamader/minskey#26]
#10 のやつ、そもそもGTLの内容取得できてなさげ

何を見てヨシって言ったんですか（実装者がカス）

`/notes/timeline`と`/notes/local-timeline`の違いis何

**Comment by yamader** [comment]
LTLとHTLじゃね
Home投稿が流れるかどうか

**Comment by Hayao0819** [comment]
`/notes/timeline`ってHTLのことか
