### ISSUE TITLE
Bug: CustomEmojiのキャッシュが動いてないかもしれない

### ISSUE THREAD

**Issue by Hayao0819** [yamader/minskey#32]
![image](https://github.com/yamader/minskey/assets/32128205/7a09b07d-5c07-4bfb-a397-f33c2b623602)

詳細不明、後で検証する

**Comment by Hayao0819** [comment]
多分直った気がする

ろくにデバッグしてないので帰宅次第やる

https://github.com/Hayao0819/minskey/commit/991597bf2b404956829929775b9ab3b65a5b1e74

**Comment by Hayao0819** [comment]
絵文字のキャッシュをカスタムフックにしたり色々しようと思って書いてる
ちょいまち

**Comment by Hayao0819** [comment]
一旦PR送る。けれどもまだ直ってないっぽいので要検証。

**Comment by yamader** [comment]
直った気がする
