### ISSUE TITLE
Bug: TLを無限に読み込み続けてメモリをめっちゃ使う

### ISSUE THREAD

**Issue by Hayao0819** [yamader/minskey#42]
軽く調査したところ`useTL`の`more`がめっちゃ呼び出されてる。

https://github.com/yamader/minskey/blob/c26bac3bdfcbddb217ab049767d3d20431bac460/src/app/(main)/(nav)/home/page.tsx#L13

`useBottom`が一生トリガーされているっぽい。

**Comment by Hayao0819** [comment]
多分ここで確認できる。 [upstream-dev](https://github.com/Hayao0819/minskey/tree/upstream-dev)をデプロイしているので。

https://minskey-upstream-dev.vercel.app/home/

**Comment by Hayao0819** [comment]
`useSize(document.body).height` と `document.body.scrollHeight`が無限に増えてる結果無限にトリガーされてるみたい

なんで増えてるんだろう

![image](https://github.com/yamader/minskey/assets/32128205/86f2a044-e179-42fc-9c48-675bcdca3548)

**Comment by yamader** [comment]
えぇ……

**Comment by yamader** [comment]
直した

**Comment by Hayao0819** [comment]
Todo:fix ってことは暫定処置みたいな感じ？

https://github.com/yamader/minskey/commit/3f99539628bb1a8cb422a90ace5bdf208dfaa001

**Comment by yamader** [comment]
fixは適当
あとで見直すかなーとおもって目印だけつけた
