### ISSUE TITLE
アイコンのレイアウトが崩れている

### ISSUE THREAD

**Issue by Hayao0819** [yamader/minskey#52]
直そうと30分程格闘して諦めた

<img width="397" alt="image" src="https://github.com/yamader/minskey/assets/32128205/00b84a1b-02f0-4b7b-a8d8-722d35acedab">

**Comment by Hayao0819** [comment]
これ他の人で発生してないってことは多分俺が設定してる画像のアスペクト比が悪いみたい

**Comment by yamader** [comment]
たぶん直った

**Comment by Hayao0819** [comment]
すげー
