### ISSUE TITLE
MiAuthでmiauth.jsを使う提案

### ISSUE THREAD

**Issue by Hayao0819** [yamader/minskey#77]
権限とかいくつかのところで微妙にmisskey-jsに依存してたので、多かれ少なかれテコ入れが必要そう。

https://github.com/Comamoca/miauth.js というのがあるが
- Next.jsで使えるか
- そもそも外部ライブラリに任せるか全て自前実装するか

の議論が必要そうなので意見を聞きたい。

**Comment by yamader** [comment]
ちっちゃそうだしいいのでは？
ただrandomUUIDが若干対応しょっぱそうなのが不安だなー(nextってjsのpolyfillあったっけ)

**Comment by Hayao0819** [comment]
わからん、確認しとく

**Comment by Hayao0819** [comment]
ちょっと色々対応しないと不味そう

https://zenn.dev/terrierscript/articles/2020-11-03-next-js-random-value

**Comment by Hayao0819** [comment]
まぁでもQuickAuthを使わなければいいだけなので、ライブラリ側に手を加える必要はなさそう

**Comment by yamader** [comment]
お

**Comment by Hayao0819** [comment]
実装してみたけど、ライブラリを使う恩恵があまり無いかも

**Comment by Hayao0819** [comment]
https://github.com/Hayao0819/minskey/commit/f46a4d72fffb956ecbaf52b5a1a6fa0da6cf7bf1

リダイレクトの受け取り側はライブラリの関数の関係で結局時前実装することになりそう

（checkの返り値のうちtokenしか取得できない）
